/**
 * Minimal decoders for the `codex app-server` messages the adapter reads, checked against bindings
 * generated by `codex app-server generate-ts` (0.160.1). Lenient: only the fields used are declared,
 * unknown fields are ignored, and a field the adapter can do without is optional and nullable.
 */
import { Option, Schema } from 'effect';

/** Optional and nullable: absent, `null` and `undefined` all mean "not known". */
const maybe = <S extends Schema.Top>(schema: S) => Schema.optionalKey(Schema.NullOr(schema));

/**
 * One `ThreadItem`, of any `type`, as one flat struct: the fields of every item kind the adapter
 * maps, all optional. Fields whose type differs between kinds (`content`, `result`) are decoded
 * loosely and read according to the item's `type`. Decode items with `itemOf`, never directly.
 */
export const Item = Schema.Struct({
  type: Schema.String,
  id: Schema.String,
  // userMessage
  clientId: maybe(Schema.String),
  // userMessage: input parts (`{type, text}`); reasoning: strings. Read only for userMessage.
  content: maybe(Schema.Array(Schema.Unknown)),
  // agentMessage, plan
  text: maybe(Schema.String),
  // commandExecution
  command: maybe(Schema.String),
  cwd: maybe(Schema.String),
  aggregatedOutput: maybe(Schema.String),
  exitCode: maybe(Schema.Number),
  // every tool item
  status: maybe(Schema.String),
  // fileChange
  changes: maybe(
    Schema.Array(
      Schema.Struct({
        path: Schema.String,
        kind: maybe(Schema.Struct({ type: Schema.String })),
        diff: maybe(Schema.String),
      }),
    ),
  ),
  // mcpToolCall, dynamicToolCall, collabAgentToolCall
  server: maybe(Schema.String),
  tool: maybe(Schema.String),
  namespace: maybe(Schema.String),
  arguments: Schema.optionalKey(Schema.Unknown),
  result: Schema.optionalKey(Schema.Unknown),
  error: maybe(Schema.Struct({ message: Schema.String })),
  contentItems: maybe(
    Schema.Array(Schema.Struct({ type: Schema.String, text: maybe(Schema.String) })),
  ),
  success: maybe(Schema.Boolean),
  // webSearch
  query: maybe(Schema.String),
  action: Schema.optionalKey(Schema.Unknown),
  // imageView, imageGeneration
  path: maybe(Schema.String),
  revisedPrompt: maybe(Schema.String),
  savedPath: maybe(Schema.String),
  failure: Schema.optionalKey(Schema.Unknown),
  // collabAgentToolCall
  receiverThreadIds: maybe(Schema.Array(Schema.String)),
  prompt: maybe(Schema.String),
  model: maybe(Schema.String),
  reasoningEffort: maybe(Schema.String),
  agentsStates: maybe(
    Schema.Record(
      Schema.String,
      Schema.Struct({ status: Schema.String, message: maybe(Schema.String) }),
    ),
  ),
  // subAgentActivity
  kind: maybe(Schema.String),
  agentThreadId: maybe(Schema.String),
  agentPath: maybe(Schema.String),
});
export type Item = typeof Item.Type;

/** Every item's identity: what remains of an item whose other fields do not decode. */
const ItemIdentity = Schema.Struct({ type: Schema.String, id: Schema.String });

const decodeFullItem = Schema.decodeUnknownOption(Item);
const decodeItemIdentity = Schema.decodeUnknownOption(ItemIdentity);

/**
 * One item, decoded on its own so that it can never make a notification or a page of history
 * unreadable: when a field has a shape the adapter does not expect, only the item's `type` and
 * `id` are kept (its content is then shown empty or left out). `undefined`: not an item at all.
 */
export const itemOf = (value: unknown): Item | undefined =>
  Option.getOrUndefined(Option.orElse(decodeFullItem(value), () => decodeItemIdentity(value)));

const ThreadScoped = { threadId: Schema.String };

const TurnNotification = Schema.Struct({
  ...ThreadScoped,
  turn: Schema.Struct({
    status: Schema.String,
    error: maybe(Schema.Struct({ codexErrorInfo: Schema.optionalKey(Schema.Unknown) })),
  }),
});

const ItemNotification = Schema.Struct({ ...ThreadScoped, item: Schema.Unknown });

const StatusNotification = Schema.Struct({
  ...ThreadScoped,
  status: Schema.Struct({ type: Schema.String }),
});

const PlanNotification = Schema.Struct({
  ...ThreadScoped,
  explanation: maybe(Schema.String),
  plan: Schema.Array(Schema.Struct({ step: Schema.String, status: Schema.String })),
});

const Window = Schema.Struct({ usedPercent: Schema.Number, resetsAt: maybe(Schema.Number) });

const RateLimitsNotification = Schema.Struct({
  rateLimits: Schema.Struct({ primary: maybe(Window), secondary: maybe(Window) }),
});

/** One server notification, as received. */
export interface Notification {
  readonly method: string;
  readonly params: unknown;
}

/** A server notification the tracker acts on, decoded. */
export type Frame =
  | { readonly _tag: 'TurnStarted'; readonly threadId: string }
  | {
      readonly _tag: 'TurnCompleted';
      readonly threadId: string;
      readonly status: string;
      /** The turn error's `codexErrorInfo`: a name, or an object keyed by the name. */
      readonly errorInfo: unknown;
    }
  | {
      readonly _tag: 'ItemStarted' | 'ItemCompleted';
      readonly threadId: string;
      readonly item: Item;
    }
  | { readonly _tag: 'ThreadStatus'; readonly threadId: string; readonly status: string }
  | {
      readonly _tag: 'PlanUpdated';
      readonly threadId: string;
      readonly explanation: string | undefined;
      readonly plan: ReadonlyArray<{ readonly step: string; readonly status: string }>;
    }
  /** The reset time of a usage window that is full, if any (the later one when both are). */
  | { readonly _tag: 'RateLimits'; readonly fullResetsAt: number | undefined };

const decode =
  <S extends Schema.Top & { readonly DecodingServices: never }>(schema: S) =>
  (params: unknown) =>
    Option.getOrUndefined(Schema.decodeUnknownOption(schema)(params));

const decodeTurn = decode(TurnNotification);
const decodeItem = decode(ItemNotification);
const decodeStatus = decode(StatusNotification);
const decodePlan = decode(PlanNotification);
const decodeRateLimits = decode(RateLimitsNotification);

const fullResetsAt = (
  windows: ReadonlyArray<typeof Window.Type | null | undefined>,
): number | undefined => {
  const resets = windows.flatMap((window) =>
    window !== null &&
    window !== undefined &&
    window.usedPercent >= 100 &&
    typeof window.resetsAt === 'number'
      ? [window.resetsAt]
      : [],
  );
  return resets.length === 0 ? undefined : Math.max(...resets);
};

/**
 * The frame of one server notification, or `undefined` for a notification the tracker ignores
 * (or one whose parameters do not decode).
 */
export const frameOf = (method: string, params: unknown): Frame | undefined => {
  switch (method) {
    case 'turn/started': {
      const turn = decodeTurn(params);
      return turn && { _tag: 'TurnStarted', threadId: turn.threadId };
    }
    case 'turn/completed': {
      const turn = decodeTurn(params);
      return (
        turn && {
          _tag: 'TurnCompleted',
          threadId: turn.threadId,
          status: turn.turn.status,
          errorInfo: turn.turn.error?.codexErrorInfo,
        }
      );
    }
    case 'item/started':
    case 'item/completed': {
      const notification = decodeItem(params);
      const item = notification && itemOf(notification.item);
      return (
        notification &&
        item && {
          _tag: method === 'item/started' ? 'ItemStarted' : 'ItemCompleted',
          threadId: notification.threadId,
          item,
        }
      );
    }
    case 'thread/status/changed': {
      const status = decodeStatus(params);
      return (
        status && { _tag: 'ThreadStatus', threadId: status.threadId, status: status.status.type }
      );
    }
    case 'turn/plan/updated': {
      const plan = decodePlan(params);
      return (
        plan && {
          _tag: 'PlanUpdated',
          threadId: plan.threadId,
          explanation: plan.explanation ?? undefined,
          plan: plan.plan,
        }
      );
    }
    case 'account/rateLimits/updated': {
      const limits = decodeRateLimits(params);
      return (
        limits && {
          _tag: 'RateLimits',
          fullResetsAt: fullResetsAt([limits.rateLimits.primary, limits.rateLimits.secondary]),
        }
      );
    }
    default:
      return undefined;
  }
};

/** The name of a `codexErrorInfo`: the string itself, or the single key of its object form. */
export const errorInfoName = (info: unknown): string | undefined => {
  if (typeof info === 'string') return info;
  if (typeof info !== 'object' || info === null) return undefined;
  const [name] = Object.keys(info);
  return name;
};

/** `thread/start` and `thread/resume` responses: the thread's ID. */
export const ThreadResponse = Schema.Struct({ thread: Schema.Struct({ id: Schema.String }) });

/** `thread/read` response: what Continue and preload need of a stored thread. */
export const ThreadReadResponse = Schema.Struct({
  thread: Schema.Struct({
    cwd: Schema.String,
    model: maybe(Schema.String),
    reasoningEffort: maybe(Schema.String),
  }),
});

/** `thread/turns/list` response: one page of turns, oldest first when asked `asc`. Items: `itemOf`. */
export const TurnsPage = Schema.Struct({
  data: Schema.Array(Schema.Struct({ items: Schema.Array(Schema.Unknown) })),
  nextCursor: maybe(Schema.String),
});
